name: assigment
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  get_storage: ^2.0.3
  flash: ^2.0.3+3
  freezed_annotation: ^2.1.0
  dartz: ^0.10.1
  flutter_svg: ^1.1.4
  shared_preferences: ^2.0.15


  flutter: 
    sdk: flutter

dev_dependencies:
  parse_server_sdk_flutter: ^3.1.3
  flutter_lints: ^2.0.0
  lints: 2.0.0
  build_runner: ^2.2.0
  freezed: ^2.1.0+1

  flutter_test: 
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2x/
    - assets/images/3x/

  fonts:
    - family: CompactBold
      fonts:
        - asset: assets/fonts/Compact-Bold.ttf
    - family: CompactRegular
      fonts:
        - asset: assets/fonts/Compact-Regular.ttf
    - family: CompactSemibold
      fonts:
        - asset: assets/fonts/Compact-Semibold.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Light.ttf